sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-secret: 6EFEmjAwJEyf7l3M0aF2BgrxwXTEpI
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: my-sky-takeout0
    access-key-id: LTAI5tJTQ3jkAVGcfs8aEp3i
  redis:
    host: 192.168.136.128
    port: 6379
    database: 2
  wechat:
    appid: wxbf8a4e6c3f299287
    secret: b38d0a13d095e270311a5b191502c0bb
